hmtWithExtraAttributes/config/routes.rb
Rails.application.routes.draw do
  resources :linkers
  resources :topics
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

hmtWithExtraAttributes/app/models/article.rb
class Article < ApplicationRecord
	has_many :linkers
	has_many :topics, :through => :linkers
end

hmtWithExtraAttributes/app/models/linker.rb
class Linker < ApplicationRecord
  belongs_to :topic
  belongs_to :article
	
	accepts_nested_attributes_for :article
end

hmtWithExtraAttributes/app/models/topic.rb
class Topic < ApplicationRecord
	has_many :linkers
	has_many :articles, :through => :linkers

	accepts_nested_attributes_for :articles
	accepts_nested_attributes_for :linkers
end

hmtWithExtraAttributes/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title)
    end
end

hmtWithExtraAttributes/app/controllers/linkers_controller.rb
class LinkersController < ApplicationController
  before_action :set_linker, only: [:show, :edit, :update, :destroy]

  # GET /linkers
  # GET /linkers.json
  def index
    @linkers = Linker.all
  end

  # GET /linkers/1
  # GET /linkers/1.json
  def show
  end

  # GET /linkers/new
  def new
    @linker = Linker.new
  end

  # GET /linkers/1/edit
  def edit
  end

  # POST /linkers
  # POST /linkers.json
  def create
    @linker = Linker.new(linker_params)

    respond_to do |format|
      if @linker.save
        format.html { redirect_to @linker, notice: 'Linker was successfully created.' }
        format.json { render :show, status: :created, location: @linker }
      else
        format.html { render :new }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linkers/1
  # PATCH/PUT /linkers/1.json
  def update
    respond_to do |format|
      if @linker.update(linker_params)
        format.html { redirect_to @linker, notice: 'Linker was successfully updated.' }
        format.json { render :show, status: :ok, location: @linker }
      else
        format.html { render :edit }
        format.json { render json: @linker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linkers/1
  # DELETE /linkers/1.json
  def destroy
    @linker.destroy
    respond_to do |format|
      format.html { redirect_to linkers_url, notice: 'Linker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linker
      @linker = Linker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linker_params
      params.require(:linker).permit(:topic_id, :article_id, :relevance)
    end
end

hmtWithExtraAttributes/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
		@topic.articles.build
		@topic.linkers.build.build_article
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:content,
				linkers_attributes: [:id, :topic_id, :article_id, :relevance, :created_at, :updated_at, :_destroy, article_attributes: [:id, :title, :created_at, :updated_at, :_destroy]]
)
    end
end

hmtWithExtraAttributes/app/helpers/articles_helper.rb
module ArticlesHelper
end

hmtWithExtraAttributes/app/helpers/linkers_helper.rb
module LinkersHelper
end

hmtWithExtraAttributes/app/helpers/topics_helper.rb
module TopicsHelper
end

hmtWithExtraAttributes/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hmtWithExtraAttributes/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

hmtWithExtraAttributes/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

hmtWithExtraAttributes/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

hmtWithExtraAttributes/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

hmtWithExtraAttributes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkedForm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

hmtWithExtraAttributes/app/views/linkers/_form.html.erb
<%= form_with(model: linker, local: true) do |form| %>
  <% if linker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linker.errors.count, "error") %> prohibited this linker from being saved:</h2>

      <ul>
      <% linker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic_id %>
    <%= form.text_field :topic_id, id: :linker_topic_id %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id, id: :linker_article_id %>
  </div>

  <div class="field">
    <%= form.label :relevance %>
    <%= form.text_field :relevance, id: :linker_relevance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

hmtWithExtraAttributes/app/views/linkers/edit.html.erb
<h1>Editing Linker</h1>

<%= render 'form', linker: @linker %>

<%= link_to 'Show', @linker %> |
<%= link_to 'Back', linkers_path %>

hmtWithExtraAttributes/app/views/linkers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linkers</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Article</th>
      <th>Relevance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linkers.each do |linker| %>
      <tr>
        <td><%= linker.topic %></td>
        <td><%= linker.article %></td>
        <td><%= linker.relevance %></td>
        <td><%= link_to 'Show', linker %></td>
        <td><%= link_to 'Edit', edit_linker_path(linker) %></td>
        <td><%= link_to 'Destroy', linker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linker', new_linker_path %>

hmtWithExtraAttributes/app/views/linkers/new.html.erb
<h1>New Linker</h1>

<%= render 'form', linker: @linker %>

<%= link_to 'Back', linkers_path %>

hmtWithExtraAttributes/app/views/linkers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @linker.topic %>
</p>

<p>
  <strong>Article:</strong>
  <%= @linker.article %>
</p>

<p>
  <strong>Relevance:</strong>
  <%= @linker.relevance %>
</p>

<%= link_to 'Edit', edit_linker_path(@linker) %> |
<%= link_to 'Back', linkers_path %>

hmtWithExtraAttributes/app/views/topics/_form.html.erb
<%= #form_with(model: topic, local: true) do |form| 
%>
<%= form_for(@topic) do |topic_form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= topic_form.label :content %>
    <%= topic_form.text_field :content, id: :topic_content %>
  </div>

	<%= topic_form.fields_for :linkers do |linker_form| %>
    <%= linker_form.label :relevance %>
    <%= linker_form.text_field :relevance, id: :linker_relevance %>
		<%= linker_form.fields_for :article do |article_form| %>
    	<%= article_form.label :title %>
    	<%= article_form.text_field :title, id: :article_title %>
		<% end %>

	<% end %>

  <div class="actions">
    <%= topic_form.submit %>
  </div>
<% end %>

hmtWithExtraAttributes/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

hmtWithExtraAttributes/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.content %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

hmtWithExtraAttributes/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

hmtWithExtraAttributes/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @topic.content %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>